version: '3.8'

services:
  python-nlp-service:
    build: ./python-nlp-service
    ports:
      - "8000:8000"

  textanalyzer-api:
    build: ./src
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - PythonNlp__BaseUrl=http://python-nlp-service:8000
    depends_on:
      - python-nlp-service